### ISSUE TITLE
Question about method implementation

### ISSUE THREAD

**Issue by MrChenFeng** [mpatacchiola/self-supervised-relational-reasoning#1]
Thanks for your work. I have one question regarding the results.
The results provided in the paper of SimCLR is much lower than the original one. 
And as you mentioned in the appendix, obviously that's because you used a very small mini-bacthsize (128). 
And as you said  the reason why you used a small batchsize 128 is to have a fair comparison, however in my calculation:
SimCLR image pairs[two transformations]: (128x2)*(128x2-1) = 65536 
The paper method[K=32 transformations]: (32x64)*((32-1)x64) = 4063232
However, you mentioned the image pairs in the paper method is ~63000.
I think you get the result by 64x32x31= 63488 based on below formula you have:
![image](https://user-images.githubusercontent.com/24207392/100091833-207a8200-2e90-11eb-8c64-24820e22462e.png)

**Comment by mpatacchiola** [comment]
Hi @MrChenFeng and thank you for your interest in our work. 

Comparison is done on the number of pairs built in representation space. In SimCLR the total number of pairs is given by `(batch_size * K)^2` where `K=2` (2 augmentations). This is in line with the number you reported `6.55 * 10^4`. In our method the total number of pairs is given by `batch_size * (K^2 - K)` which corresponds to `6.3 * 10^4` when using a mini-batch of 64 images and `K=32` augmentations. The figure is slightly lower than the one in SimCLR. This is better described in Section 3.1 of the paper and in the discussion in Section 5.

I can try to clarify how we build the pairs. For each one of the `K` mini-batches, we take each image in mini-batch `1` and couple it with the correspondent augmentation in mini-batches `2, ..., K` to build the positive pairs. We repeat the same process to build the negative pairs by coupling each image with a random image in the next mini-batch. The same procedure is repeated for mini-batch `2` which is coupled with the mini-batches `3,...,K`, and so on.  This corresponds to a total of  `batch_size * (K^2 - K)` pairs. 

This process would be clear if you give a look at our code [here](https://github.com/mpatacchiola/self-supervised-relational-reasoning/blob/019d5760a9f8e404623836d2e6ab47c3878f0280/essential_script.py#L137). In particular, if you check [this line](https://github.com/mpatacchiola/self-supervised-relational-reasoning/blob/019d5760a9f8e404623836d2e6ab47c3878f0280/essential_script.py#L142), you can see the two `for` loops  which are building the pairs in the aggregation function by iterating two times over the `K` augmentations with a final cost of `K^2` as explained above. 

Hope this helped.
