### ISSUE TITLE
Problem in understanding dataloader

### ISSUE THREAD

**Issue by shivam-chandhok** [mpatacchiola/self-supervised-relational-reasoning#4]
Hi,

I see that you get positive pairs as data augmentations of same samples and to get negative pairs you use roll.
However, wouldn't this cause problem if 2 consecutive samples of same class are present in a batch.

What I mean is, currently the assumption is that we get (for K=3 say) c1d1 c2d1 c3d1, c1d2 c2d2 c3d2, c1d3 c2d3 c3d3 kind of batch (where ci is the class and di is the ith data-aug of that class). However, what if the 2 consecutive samples have same classes and we end up with c1d1 c1d1 c3d1, c1d2 c1d2 c3d2, c1d3 c1d3 c3d3.
Now, the roll doesn't lead to negative pairs for the group (c1d1 c1d1 c3d1) and (c1d2 c1d2 c3d2)

**Comment by mpatacchiola** [comment]
Hi @shivam-chandhok what you are pointing out is not a problem in practice. The probability of a colliding pair is 1/10 on CIFAR-10, 1/100 on CIFAR-100, and 1/1000 on ImageNet. I did some experiments in correcting this bias but the gains are minimal. Note that the same assumption has been made in papers like SimCLR.

**Comment by mpatacchiola** [comment]
Closed for inactivity.
