### ISSUE TITLE
Could you please tell me how to deduce equation 4 in your paper

### ISSUE THREAD

**Issue by xiaominli1020** [mpatacchiola/self-supervised-relational-reasoning#5]
Could you please tell me how to deduce equation 4 in your paper?
![image](https://user-images.githubusercontent.com/25433111/121811442-0458f980-cc97-11eb-8763-e440c35f1fd2.png)

**Comment by mpatacchiola** [comment]
Hi there, sorry for the late reply.

The most intuitive way to understand that equation is too look at how pairs are aggregated, see code [here](https://github.com/mpatacchiola/self-supervised-relational-reasoning/blob/071f1867b54fe2e0fe450535615f9133a8793385/methods/relationnet.py#L98).
